// Map slider values to years
const yearMap = {
  1: "1500BC",
  2: "1000BC",
  3: "800BC",
  4: "600BC",
  5: "400BC",
  6: "200BC",
  7: "1AD",
  8: "100AD",
  9: "200AD",
  10: "300AD",
  11: "400AD",
  12: "500AD",
  13: "600AD",
  14: "700AD",
  15: "800AD",
};

// Initialize the map
const map = L.map("map").setView([50, 10], 4); // Centered on Europe

// Add tile layer to map
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: "&copy; OpenStreetMap contributors",
}).addTo(map);

// Define markers data for each time period
const markersData = {
  "1500BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Greek",
    },
    {
      lat: 37.4556,
      lon: 22.4702,
      language: "Hellenic",
      region: "Balkans",
      notes: "Eastern Greek",
    },
    {
      lat: 39.1021,
      lon: 22.2848,
      language: "Hellenic",
      region: "Balkans",
      notes: "Central Greek",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Hittite",
    },
    {
      lat: 39.4201,
      lon: 27.373,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Proto-Lydian",
    },
    {
      lat: 37.2327,
      lon: 34.1258,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwic",
    },
    {
      lat: 41.03,
      lon: 31.4927,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Palaic",
    },
    {
      lat: 46.3644,
      lon: 13.4428,
      language: "Italic",
      region: "",
      notes: "Ancestor to all Italic/Romance languages",
    },
    {
      lat: 47.243,
      lon: 5.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to all Celtic languages.",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Iberian",
      region: "Iberian Peninsula",
      notes: "Iberian languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 58.5106,
      lon: 42.3848,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Finno-Ugric Languages",
    },
  ],
  "1000BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Greek",
    },
    {
      lat: 37.4556,
      lon: 22.4702,
      language: "Hellenic",
      region: "Balkans",
      notes: "Eastern Greek",
    },
    {
      lat: 39.1021,
      lon: 22.2848,
      language: "Hellenic",
      region: "Balkans",
      notes: "Central Greek",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "",
      notes: "Ancestor to all Italic/Romance languages",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to all Celtic languages.",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Iberian",
      region: "Iberian Peninsula",
      notes: "Iberian languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
  ],
  "800BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian",
      notes: "Ionic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 42.2948,
      lon: 13.5312,
      language: "Italic",
      region: "Italy",
      notes: "Italic languages",
    },
    {
      lat: 50.5843,
      lon: 0.2126,
      language: "Celtic",
      region: "Britian, Ireland, Gaul, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Iberian",
      region: "Iberian Peninsula",
      notes: "Iberian languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
  ],
  "600BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy",
      notes: "Ionic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 36.4202,
      lon: 31.47,
      language: "Hellenic",
      region: "Anatolia",
      notes: "Pamphylian",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.1507,
      lon: 29.4859,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Milyan",
    },
    {
      lat: 37.0223,
      lon: 33.2221,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Sidetic",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latino-Faliscan",
    },
    {
      lat: 42.2948,
      lon: 13.5312,
      language: "Italic",
      region: "Italy",
      notes: "Osco-Umbrian",
    },
    {
      lat: 37.3541,
      lon: 14.3639,
      language: "Italic",
      region: "Sicely",
      notes: "Sicel",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Ireland, Gaul, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 42.0855,
      lon: -7.4438,
      language: "Iberian",
      region: "Iberian Peninsula",
      notes: "Iberian languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania, Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
  ],
  "400BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Gaul, Iberia, Eastern Europe",
      notes: "Ionic-Attic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 36.4202,
      lon: 31.47,
      language: "Hellenic",
      region: "Anatolia",
      notes: "Pamphylian",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.1507,
      lon: 29.4859,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Milyan",
    },
    {
      lat: 37.0223,
      lon: 33.2221,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Sidetic",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latin",
    },
    {
      lat: 42.385,
      lon: 12.0906,
      language: "Italic",
      region: "Italy",
      notes: "Faliscan",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 43.2355,
      lon: 13.0018,
      language: "Italic",
      region: "Italy",
      notes: "Umbrian",
    },
    {
      lat: 37.3541,
      lon: 14.3639,
      language: "Italic",
      region: "Sicely",
      notes: "Sicel",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Ireland, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Iberia, Central Europe",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 42.0855,
      lon: -7.4438,
      language: "Iberian",
      region: "Iberian Peninsula",
      notes: "Iberian languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania, Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Volgaic Languages",
    },
  ],
  "200BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Iberia, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans",
      notes: "Arcadocypriot",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latin",
    },
    {
      lat: 42.385,
      lon: 12.0906,
      language: "Italic",
      region: "Italy",
      notes: "Faliscan",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 43.2355,
      lon: 13.0018,
      language: "Italic",
      region: "Italy",
      notes: "Umbrian",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Iberian, Celtic",
      region: "Iberian Peninsula",
      notes: "Iberian and Celtic languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Central Europe",
      notes: "West Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Volgaic Languages",
    },
  ],
  "1AD": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 45.0302,
      lon: 10.1812,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa",
      notes: "Vulgar Latin",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Central Europe",
      notes: "West Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Gaul, Iberia",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "100AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "200AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "300AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 41.4623,
      lon: -5.2719,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "400AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 41.4623,
      lon: -5.2719,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "500AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe, Middle East",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Southern Europe, Anatolia",
      notes: "Lste Latin",
    },
    {
      lat: 43.0118,
      lon: -0.1547,
      language: "Italic",
      region: "Gaul, Iberia",
      notes: "Western Romance",
    },
    {
      lat: 43.3408,
      lon: 23.2006,
      language: "Italic",
      region: "Eastern Europe, Southern Europe",
      notes: "Eastern Romance",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "600AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Southern Europe, Anatolia",
      notes: "Late Latin",
    },
    {
      lat: 43.0118,
      lon: -0.1547,
      language: "Italic",
      region: "Gaul, Iberia",
      notes: "Western Romance",
    },
    {
      lat: 43.3408,
      lon: 23.2006,
      language: "Italic",
      region: "Eastern Europe, Southern Europe",
      notes: "Eastern Romance",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe, Southern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "700AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Europe",
      notes: "Medieval Latin",
    },
    {
      lat: 45.4222,
      lon: 2.3952,
      language: "Italic",
      region: "Gaul",
      notes: "Gallo-Romance",
    },
    {
      lat: 39.3525,
      lon: -4.4545,
      language: "Italic",
      region: "Iberia",
      notes: "Iberian Romance",
    },
    {
      lat: 44.29,
      lon: 25.0135,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Proto-Romanian",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 53.0555,
      lon: 11.3932,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Saxon",
    },
    {
      lat: 48.265,
      lon: 13.1328,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old High German",
    },
    {
      lat: 52.3207,
      lon: 1.3315,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "Anglo-Frisian Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Low Franconian",
    },
    {
      lat: 38.3047,
      lon: -3.3127,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 55.2657,
      lon: 11.3002,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe, Southern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
  "800AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Europe",
      notes: "Medieval Latin",
    },
    {
      lat: 45.4222,
      lon: 2.3952,
      language: "Italic",
      region: "Gaul",
      notes: "Gallo-Romance",
    },
    {
      lat: 39.3525,
      lon: -4.4545,
      language: "Italic",
      region: "Iberia",
      notes: "Iberian Romance",
    },
    {
      lat: 44.29,
      lon: 25.0135,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Romanian",
    },
    {
      lat: 41.4617,
      lon: 20.5221,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Aromanian",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 53.0555,
      lon: 11.3932,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Saxon",
    },
    {
      lat: 48.265,
      lon: 13.1328,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old High German",
    },
    {
      lat: 52.3207,
      lon: 1.3315,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "Old English",
    },
    {
      lat: 53.381,
      lon: 7.262,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Frisian",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Low Franconian",
    },
    {
      lat: 45.2648,
      lon: 34.3536,
      language: "Germanic",
      region: "Eastern Europe",
      notes: "Crimean Gothic",
    },
    {
      lat: 59.3822,
      lon: 7.5959,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old West Norse",
    },
    {
      lat: 57.3802,
      lon: 18.362,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Gutnish",
    },
    {
      lat: 55.2657,
      lon: 11.3002,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old East Norse",
    },
    {
      lat: 57.474,
      lon: -3.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Irish",
    },
    {
      lat: 48.0833,
      lon: -3.3056,
      language: "Celtic",
      region: "Brittany",
      notes: "Breton",
    },
    {
      lat: 50.4829,
      lon: -3.4531,
      language: "Celtic",
      region: "Cornwall",
      notes: "Cornish",
    },
    {
      lat: 52.3511,
      lon: -3.2041,
      language: "Celtic",
      region: "Wales",
      notes: "Welsh",
    },
    {
      lat: 54.2338,
      lon: -2.5716,
      language: "Celtic",
      region: "Crumbria",
      notes: "Cumbric",
    },
    {
      lat: 56.2523,
      lon: -5.595,
      language: "Celtic",
      region: "North Britian",
      notes: "Scottish Gaelic",
    },
    {
      lat: 54.1359,
      lon: -4.3508,
      language: "Celtic",
      region: "Mann",
      notes: "Manx",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "East Slavic languages.",
    },
    {
      lat: 51.5227,
      lon: 19.0904,
      language: "Slavic",
      region: "Central Europe",
      notes: "West Slavic languages.",
    },
    {
      lat: 43.452,
      lon: 23.0842,
      language: "Slavic",
      region: "Southern Europe",
      notes: "South Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 60.2943,
      lon: 24.0434,
      language: "Uralic",
      region: "Northern Europe",
      notes: "Finnish",
    },
    {
      lat: 62.0607,
      lon: 32.2222,
      language: "Uralic",
      region: "Northern Europe",
      notes: "Karelian",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Estonian",
    },
    {
      lat: 57.0457,
      lon: 22.3607,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Livonian",
    },
    {
      lat: 47.0626,
      lon: 48.2545,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Hungarian",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
  ],
};

// Map of language to color
const languageColorMap = {
  Latin: "blue",
  Italic: "blue",
  Celtic: "green",
  Germanic: "red",
  Iberian: "purple",
  Slavic: "yellow",
  Baltic: "orange",
  Anatolian: "brown",
  Hellenic: "teal",
  Uralic: "turquoise",
};

// Function to create a marker with a custom color based on the language
function getLanguageMarkerColor(language) {
  return languageColorMap[language] || "gray"; // Default to gray if the language is not in the map
}

// Function to load language data and display markers with different colors
function loadLanguageData(year) {
  // Clear any existing markers on the map
  map.eachLayer((layer) => {
    if (layer instanceof L.Marker || layer instanceof L.CircleMarker) {
      map.removeLayer(layer); // Remove all markers (both L.Marker and L.CircleMarker)
    }
  });

  // Load markers for the selected year
  const markers = markersData[year]; // Get the markers for the selected year

  markers.forEach((marker) => {
    const markerColor = getLanguageMarkerColor(marker.language); // Get the color based on the language

    // Create a circle marker with the color based on the language
    L.circleMarker([marker.lat, marker.lon], {
      color: markerColor,
      fillColor: markerColor,
      fillOpacity: 0.5,
      radius: 8, // Size of the marker
    })
      .addTo(map)
      .bindPopup(
        `<b>${marker.language}</b><br>${marker.region}<br>${marker.notes}`
      );
  });
}

// Get slider and year label elements
const slider = document.getElementById("timeSlider");
const yearLabel = document.getElementById("yearLabel");
const playButton = document.getElementById("playButton");

let intervalId; // To store the interval ID
let isPlaying = false; // To track if the play button is active

// Set the slider's max value to 5 to match the years in yearMap
slider.max = 15;

// Event listener for the slider input
slider.addEventListener("input", (event) => {
  const yearKey = yearMap[event.target.value];
  yearLabel.textContent = yearKey.replace("BC", " BC").replace("AD", " AD");
  loadLanguageData(yearKey); // Load the markers for the selected year
});

// Event listener for the Play button
playButton.addEventListener("click", () => {
  if (isPlaying) {
    clearInterval(intervalId); // Stop the interval if it's running
    playButton.textContent = "Play"; // Change button text back to "Play"
    isPlaying = false;
  } else {
    isPlaying = true;
    playButton.textContent = "Pause"; // Change button text to "Pause"

    let currentValue = parseInt(slider.value); // Get the current slider value
    const maxValue = parseInt(slider.max); // Get the maximum slider value

    intervalId = setInterval(() => {
      if (currentValue <= maxValue) {
        const yearKey = yearMap[currentValue];
        yearLabel.textContent = yearKey
          .replace("BC", " BC")
          .replace("AD", " AD");
        loadLanguageData(yearKey); // Load the markers for the current year
        slider.value = currentValue; // Update the slider to match
        currentValue += 1; // Move to the next year
      } else {
        clearInterval(intervalId); // Stop the interval when the max is reached
        playButton.textContent = "Play"; // Reset the button text
        isPlaying = false;
      }
    }, 2000); // Change year every 2 seconds (adjust as needed)
  }
});

// Initial load for 1500 BC
loadLanguageData("1500BC");
